[package]
name = "day08"
version.workspace = true
edition.workspace = true

[dependencies]
uuid = { version = "1.0", features = ["v4", "serde"] } # "serde" feature is for serialization/deserialization