name = "advent_of_code_2025"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
